<div style="
background:#FFF1F5;
border:4px solid #D8A7B1;
border-radius:22px;
padding:35px;
text-align:center;">

<h1 style="color:#8A5A66;font-family:Georgia;">
Synthetic Student Data Generation
</h1>

<p style="color:#A06A78;font-size:18px;">
SQL • Python • Pandas • NumPy
</p>

<hr style="border:1px solid #E7C7D0;">

<p style="color:#7D5A63;font-size:17px;">
10,000 Synthetic Student Records
</p>

<p style="color:#9A7380;">
CSV Dataset for SQL Practice & Data Analysis
</p>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Project Description
</h2>

<p style="
color:#6F5C63;
font-size:16px;
line-height:1.8;
text-align:justify;">

This project focuses on generating a <b>synthetic student dataset</b> using Python. The dataset contains <b>10,000 records</b> with realistic student information created for educational purposes. Since the data is artificially generated, it ensures privacy while providing a practical dataset for learning.

The generated dataset is exported as a <b>CSV file</b> and can be used for <b>SQL practice, database testing, data analysis, and data visualization</b> in a secure and efficient manner.

</p>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Project Objectives
</h2>

<ul style="
color:#6F5C63;
font-size:16px;
line-height:1.8;">

<li>Generate a synthetic student dataset containing <b>10,000 records</b>.</li>

<li>Create realistic student information using <b>Python</b>.</li>

<li>Export the generated dataset as a <b>CSV file</b>.</li>

<li>Support <b>SQL practice</b>, database testing, and data analysis.</li>

<li>Ensure data privacy by using completely synthetic information.</li>

</ul>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Key Features
</h2>

<ul style="
color:#6F5C63;
font-size:16px;
line-height:1.8;">

<li>Generated <b>10,000 synthetic student records</b>.</li>

<li>Ensured complete data privacy by using artificial data.</li>

<li>Created a structured dataset for SQL practice.</li>

<li>Exported the dataset in CSV format.</li>

<li>Suitable for database testing and data analysis.</li>

</ul>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Dataset Statistics
</h2>

<p style="
color:#6F5C63;
font-size:16px;
line-height:1.8;
text-align:justify;">

This section provides a statistical summary of the numerical columns in the dataset, including count, mean, standard deviation, minimum, maximum, and percentile values. It helps in understanding the overall distribution and characteristics of the generated data.

</p>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Output
</h2>

<p style="
color:#6F5C63;
font-size:16px;
line-height:1.8;
text-align:justify;">

The output of this project is a <b>synthetic student dataset</b> containing <b>10,000 records</b>. The generated dataset is displayed in a structured tabular format using a Pandas DataFrame, making it suitable for SQL practice, database testing, and data analysis.

</p>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Future Scope
</h2>

<p style="
color:#6F5C63;
font-size:16px;
line-height:1.8;
text-align:justify;">

This project can be extended by adding more student attributes, generating larger datasets, integrating with SQL databases, and performing advanced data analysis or visualization. It can also be used to test database performance and support machine learning experiments.

</p>

</div>

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-radius:12px;
padding:28px 30px;
margin:10px 0;">

<h2 style="
color:#8A5A66;
margin-top:0;">
Key Takeaways
</h2>

<ul style="
color:#6F5C63;
font-size:16px;
line-height:1.8;">

<li>Successfully generated a synthetic student dataset with 10,000 records.</li>

<li>Learned to organize and manage data using Python and Pandas.</li>

<li>Created a structured dataset suitable for SQL practice and analysis.</li>

<li>Improved understanding of synthetic data generation techniques.</li>

</ul>

</div>

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Creating the Synthetic Dataset
</h4>
</div>

In [47]:
import numpy as np 
import pandas as pd 
np.random.seed(54)
n_student = 10000

data = {
  
    "name" : np.random.choice(["DEV","HARSHU","NISHU","HARSHIKA"], n_student),
    "age" : np.random.randint(18, 25, n_student),
    "city" : np.random.choice(["Ambala","radaur","yamunanagar","ladwa","delhi"])
}
df = pd.DataFrame(data)
df

          name  age         city
0     HARSHIKA   21  yamunanagar
1       HARSHU   20  yamunanagar
2        NISHU   18  yamunanagar
3     HARSHIKA   18  yamunanagar
4     HARSHIKA   22  yamunanagar
...        ...  ...          ...
9995     NISHU   21  yamunanagar
9996       DEV   20  yamunanagar
9997    HARSHU   19  yamunanagar
9998    HARSHU   22  yamunanagar
9999       DEV   24  yamunanagar

[10000 rows x 3 columns]

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Importing the library
</h4>
</div>

In [32]:
import sqlite3 as sql
import pandas as pd

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Creat the database connection
</h4>
</div>

In [33]:
#connect to a database[creat if it doesnot exist]
connection = sql.connect('demo7.db')

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Creat the cursor object
</h4>
</div>

In [34]:
#creat a cursor object using the connection
cursor = connection.cursor()
#cursor helps you to traverse over the records in a db

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Creating database table
</h4>
</div>

In [35]:
cursor.execute('''CREATE TABLE paro(
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER,
    city TEXT           
);''')

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Commiting change 
</h4>
</div>

In [36]:
connection.commit()

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Inserting data into database
</h4>
</div>

In [40]:
student_data= list(df.itertuples(index=False , name = None))
cursor.executemany('''INSERT INTO paro(name, age, city) VALUES (?,?,?)''', student_data)
connection.commit()

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Fetching data from database
</h4>
</div>

In [41]:
cursor.execute('''SELECT * FROM paro''')

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Retrieving query result
</h4>
</div>

In [42]:
results = cursor.fetchall()

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Displaying retrieved data 
</h4>
</div>

In [43]:
for record in results:
    print(record)

(1, 'HARSHIKA', 21, 'yamunanagar')
(2, 'HARSHU', 20, 'yamunanagar')
(3, 'NISHU', 18, 'yamunanagar')
(4, 'HARSHIKA', 18, 'yamunanagar')
(5, 'HARSHIKA', 22, 'yamunanagar')
(6, 'HARSHU', 18, 'yamunanagar')
(7, 'DEV', 23, 'yamunanagar')
(8, 'DEV', 20, 'yamunanagar')
(9, 'HARSHIKA', 19, 'yamunanagar')
(10, 'HARSHU', 24, 'yamunanagar')
(11, 'HARSHU', 23, 'yamunanagar')
(12, 'NISHU', 19, 'yamunanagar')
(13, 'HARSHU', 18, 'yamunanagar')
(14, 'HARSHIKA', 23, 'yamunanagar')
(15, 'DEV', 21, 'yamunanagar')
(16, 'DEV', 24, 'yamunanagar')
(17, 'DEV', 18, 'yamunanagar')
(18, 'HARSHU', 18, 'yamunanagar')
(19, 'NISHU', 23, 'yamunanagar')
(20, 'NISHU', 22, 'yamunanagar')
(21, 'DEV', 18, 'yamunanagar')
(22, 'NISHU', 19, 'yamunanagar')
(23, 'DEV', 23, 'yamunanagar')
(24, 'NISHU', 24, 'yamunanagar')
(25, 'DEV', 21, 'yamunanagar')
(26, 'HARSHU', 21, 'yamunanagar')
(27, 'HARSHIKA', 20, 'yamunanagar')
(28, 'HARSHIKA', 21, 'yamunanagar')
(29, 'NISHU', 24, 'yamunanagar')
(30, 'HARSHU', 22, 'yamunanagar')
(31, 'NISHU', 24, 'yamunanagar')
(32, 'NISHU', 23, 'yamunanagar')
(33, 'DEV', 19, 'yamunanagar')
(34, 'HARSHU', 23, 'yamunanagar')
(35, 'HARSHIKA', 23, 'yamunanagar')
(36, 'NISHU', 19, 'yamunanagar')
(37, 'DEV', 19, 'yamunanagar')
(38, 'HARSHU', 20, 'yamunanagar')
(39, 'HARSHIKA', 21, 'yamunanagar')
(40, 'HARSHIKA', 24, 'yamunanagar')
(41, 'DEV', 23, 'yamunanagar')
(42, 'NISHU', 22, 'yamunanagar')
(43, 'HARSHIKA', 18, 'yamunanagar')
(44, 'HARSHIKA', 22, 'yamunanagar')
(45, 'DEV', 18, 'yamunanagar')
(46, 'HARSHIKA', 20, 'yamunanagar')
(47, 'NISHU', 18, 'yamunanagar')
(48, 'HARSHIKA', 24, 'yamunanagar')
(49, 'HARSHU', 24, 'yamunanagar')
(50, 'HARSHIKA', 23, 'yamunanagar')
(51, 'DEV', 20, 'yamunanagar')
(52, 'HARSHIKA', 24, 'yamunanagar')
(53, 'HARSHU', 19, 'yamunanagar')
(54, 'DEV', 19, 'yamunanagar')
(55, 'HARSHU', 21, 'yamunanagar')
(56, 'HARSHIKA', 19, 'yamunanagar')
(57, 'HARSHU', 20, 'yamunanagar')
(58, 'DEV', 21, 'yamunanagar')
(59, 'HARSHU', 19, 'yamunanagar')
(60, 'HARSHIKA', 22, 'yamunanagar')
(61, 'HARSHIKA', 19, 'yamunanagar')
(62, 'DEV', 18, 'yamunanagar')
(63, 'NISHU', 19, 'yamunanagar')
(64, 'NISHU', 24, 'yamunanagar')
(65, 'HARSHU', 21, 'yamunanagar')
(66, 'DEV', 22, 'yamunanagar')
(67, 'NISHU', 21, 'yamunanagar')
(68, 'HARSHIKA', 21, 'yamunanagar')
(69, 'HARSHIKA', 21, 'yamunanagar')
(70, 'HARSHU', 21, 'yamunanagar')
(71, 'DEV', 21, 'yamunanagar')
(72, 'HARSHU', 22, 'yamunanagar')
(73, 'HARSHIKA', 23, 'yamunanagar')
(74, 'NISHU', 24, 'yamunanagar')
(75, 'HARSHU', 23, 'yamunanagar')
(76, 'HARSHU', 18, 'yamunanagar')
(77, 'HARSHIKA', 22, 'yamunanagar')
(78, 'DEV', 18, 'yamunanagar')
(79, 'NISHU', 20, 'yamunanagar')
(80, 'HARSHU', 21, 'yamunanagar')
(81, 'NISHU', 23, 'yamunanagar')
(82, 'DEV', 20, 'yamunanagar')
(83, 'HARSHIKA', 22, 'yamunanagar')
(84, 'HARSHU', 23, 'yamunanagar')
(85, 'DEV', 24, 'yamunanagar')
(86, 'NISHU', 20, 'yamunanagar')
(87, 'DEV', 19, 'yamunanagar')
(88, 'DEV', 24, 'yamunanagar')
(89, 'DEV', 21, 'yamunanagar')
(90, 'HARSHIKA', 20, 'yamunanagar')
(91, 'HARSHIKA', 20, 'yamunanagar')
(92, 'HARSHIKA', 19, 'yamunanagar')
(93, 'DEV', 18, 'yamunanagar')
(94, 'HARSHIKA', 18, 'yamunanagar')
(95, 'DEV', 23, 'yamunanagar')
(96, 'NISHU', 18, 'yamunanagar')
(97, 'DEV', 21, 'yamunanagar')
(98, 'HARSHU', 19, 'yamunanagar')
(99, 'NISHU', 21, 'yamunanagar')
(100, 'DEV', 22, 'yamunanagar')
(101, 'NISHU', 24, 'yamunanagar')
(102, 'DEV', 19, 'yamunanagar')
(103, 'NISHU', 23, 'yamunanagar')
(104, 'NISHU', 24, 'yamunanagar')
(105, 'NISHU', 18, 'yamunanagar')
(106, 'HARSHIKA', 19, 'yamunanagar')
(107, 'HARSHIKA', 22, 'yamunanagar')
(108, 'HARSHU', 19, 'yamunanagar')
(109, 'NISHU', 19, 'yamunanagar')
(110, 'DEV', 18, 'yamunanagar')
(111, 'HARSHIKA', 18, 'yamunanagar')
(112, 'DEV', 23, 'yamunanagar')
(113, 'HARSHU', 23, 'yamunanagar')
(114, 'HARSHIKA', 21, 'yamunanagar')
(115, 'HARSHIKA', 22, 'yamunanagar')
(116, 'HARSHIKA', 23, 'yamunanagar')
(117, 'DEV', 18, 'yamunanagar')
(118, 'HARSHU', 18, 'yamunanagar')
(119, 'NISHU', 21, 'yamunanagar')
(120, 'HARSHU', 23, 'yamunanagar')
(121, 'HARSHIKA', 18, 'yamunanagar')
(122, 'HARSHIKA', 21, 'yamunanagar')
(123, 'DEV', 18, 'yamunanagar')
(124, 'NISHU', 22, 'yamunanagar')
(125, 'HARSHU', 22, 'yamunanagar')
(126, 'NISHU', 18, 'yamunanagar')
(127, 'DEV', 24, 'yamunanagar')
(128, 'NISHU', 21, 'yamunanagar')
(129, 'NISHU', 21, 'yamunanagar')
(130, 'NISHU', 19, 'yamunanagar')
(131, 'DEV', 18, 'yamunanagar')
(132, 'HARSHU', 20, 'yamunanagar')
(133, 'DEV', 20, 'yamunanagar')
(134, 'HARSHU', 22, 'yamunanagar')
(135, 'NISHU', 19, 'yamunanagar')
(136, 'DEV', 22, 'yamunanagar')
(137, 'HARSHU', 20, 'yamunanagar')
(138, 'HARSHIKA', 18, 'yamunanagar')
(139, 'HARSHIKA', 24, 'yamunanagar')
(140, 'DEV', 24, 'yamunanagar')
(141, 'DEV', 21, 'yamunanagar')
(142, 'DEV', 19, 'yamunanagar')
(143, 'NISHU', 18, 'yamunanagar')
(144, 'HARSHU', 22, 'yamunanagar')
(145, 'HARSHU', 19, 'yamunanagar')
(146, 'NISHU', 24, 'yamunanagar')
(147, 'DEV', 18, 'yamunanagar')
(148, 'NISHU', 19, 'yamunanagar')
(149, 'HARSHIKA', 21, 'yamunanagar')
(150, 'NISHU', 22, 'yamunanagar')
(151, 'DEV', 18, 'yamunanagar')
(152, 'HARSHIKA', 18, 'yamunanagar')
(153, 'HARSHU', 18, 'yamunanagar')
(154, 'DEV', 22, 'yamunanagar')
(155, 'HARSHIKA', 20, 'yamunanagar')
(156, 'HARSHIKA', 22, 'yamunanagar')
(157, 'HARSHIKA', 18, 'yamunanagar')
(158, 'NISHU', 22, 'yamunanagar')
(159, 'NISHU', 24, 'yamunanagar')
(160, 'NISHU', 22, 'yamunanagar')
(161, 'DEV', 22, 'yamunanagar')
(162, 'HARSHU', 24, 'yamunanagar')
(163, 'HARSHIKA', 24, 'yamunanagar')
(164, 'DEV', 21, 'yamunanagar')
(165, 'NISHU', 22, 'yamunanagar')
(166, 'HARSHU', 21, 'yamunanagar')
(167, 'HARSHU', 18, 'yamunanagar')
(168, 'HARSHU', 24, 'yamunanagar')
(169, 'HARSHU', 21, 'yamunanagar')
(170, 'HARSHIKA', 24, 'yamunanagar')
(171, 'NISHU', 21, 'yamunanagar')
(172, 'NISHU', 19, 'yamunanagar')
(173, 'DEV', 18, 'yamunanagar')
(174, 'HARSHIKA', 21, 'yamunanagar')
(175, 'NISHU', 20, 'yamunanagar')
(176, 'DEV', 19, 'yamunanagar')
(177, 'HARSHU', 20, 'yamunanagar')
(178, 'HARSHU', 20, 'yamunanagar')
(179, 'HARSHU', 19, 'yamunanagar')
(180, 'HARSHIKA', 20, 'yamunanagar')
(181, 'HARSHU', 19, 'yamunanagar')
(182, 'DEV', 21, 'yamunanagar')
(183, 'DEV', 20, 'yamunanagar')
(184, 'HARSHU', 21, 'yamunanagar')
(185, 'DEV', 24, 'yamunanagar')
(186, 'HARSHU', 21, 'yamunanagar')
(187, 'HARSHIKA', 22, 'yamunanagar')
(188, 'NISHU', 19, 'yamunanagar')
(189, 'NISHU', 23, 'yamunanagar')
(190, 'HARSHU', 22, 'yamunanagar')
(191, 'HARSHIKA', 22, 'yamunanagar')
(192, 'NISHU', 18, 'yamunanagar')
(193, 'HARSHIKA', 19, 'yamunanagar')
(194, 'DEV', 24, 'yamunanagar')
(195, 'NISHU', 20, 'yamunanagar')
(196, 'NISHU', 19, 'yamunanagar')
(197, 'NISHU', 23, 'yamunanagar')
(198, 'HARSHU', 24, 'yamunanagar')
(199, 'DEV', 18, 'yamunanagar')
(200, 'DEV', 18, 'yamunanagar')
(201, 'HARSHU', 20, 'yamunanagar')
(202, 'HARSHU', 19, 'yamunanagar')
(203, 'NISHU', 20, 'yamunanagar')
(204, 'NISHU', 19, 'yamunanagar')
(205, 'HARSHU', 23, 'yamunanagar')
(206, 'HARSHU', 18, 'yamunanagar')
(207, 'HARSHIKA', 20, 'yamunanagar')
(208, 'HARSHU', 18, 'yamunanagar')
(209, 'NISHU', 23, 'yamunanagar')
(210, 'HARSHU', 21, 'yamunanagar')
(211, 'HARSHIKA', 24, 'yamunanagar')
(212, 'HARSHU', 22, 'yamunanagar')
(213, 'NISHU', 19, 'yamunanagar')
(214, 'HARSHU', 22, 'yamunanagar')
(215, 'NISHU', 18, 'yamunanagar')
(216, 'NISHU', 19, 'yamunanagar')
(217, 'NISHU', 19, 'yamunanagar')
(218, 'NISHU', 20, 'yamunanagar')
(219, 'HARSHU', 24, 'yamunanagar')
(220, 'NISHU', 20, 'yamunanagar')
(221, 'NISHU', 24, 'yamunanagar')
(222, 'DEV', 21, 'yamunanagar')
(223, 'DEV', 23, 'yamunanagar')
(224, 'NISHU', 22, 'yamunanagar')
(225, 'HARSHIKA', 24, 'yamunanagar')
(226, 'HARSHU', 23, 'yamunanagar')
(227, 'NISHU', 18, 'yamunanagar')
(228, 'DEV', 23, 'yamunanagar')
(229, 'NISHU', 20, 'yamunanagar')
(230, 'HARSHIKA', 23, 'yamunanagar')
(231, 'HARSHIKA', 18, 'yamunanagar')
(232, 'HARSHIKA', 23, 'yamunanagar')
(233, 'DEV', 18, 'yamunanagar')
(234, 'NISHU', 19, 'yamunanagar')
(235, 'HARSHIKA', 19, 'yamunanagar')
(236, 'HARSHIKA', 18, 'yamunanagar')
(237, 'NISHU', 19, 'yamunanagar')
(238, 'DEV', 23, 'yamunanagar')
(239, 'HARSHIKA', 22, 'yamunanagar')
(240, 'HARSHU', 24, 'yamunanagar')
(241, 'HARSHU', 20, 'yamunanagar')
(242, 'DEV', 20, 'yamunanagar')
(243, 'DEV', 22, 'yamunanagar')
(244, 'NISHU', 20, 'yamunanagar')
(245, 'HARSHIKA', 21, 'yamunanagar')
(246, 'NISHU', 18, 'yamunanagar')
(247, 'HARSHIKA', 18, 'yamunanagar')
(248, 'DEV', 18, 'yamunanagar')
(249, 'HARSHIKA', 21, 'yamunanagar')
(250, 'NISHU', 22, 'yamunanagar')
(251, 'NISHU', 18, 'yamunanagar')
(252, 'HARSHIKA', 24, 'yamunanagar')
(253, 'NISHU', 19, 'yamunanagar')
(254, 'HARSHIKA', 21, 'yamunanagar')
(255, 'NISHU', 23, 'yamunanagar')
(256, 'NISHU', 18, 'yamunanagar')
(257, 'HARSHU', 24, 'yamunanagar')
(258, 'NISHU', 20, 'yamunanagar')
(259, 'DEV', 23, 'yamunanagar')
(260, 'HARSHIKA', 21, 'yamunanagar')
(261, 'NISHU', 21, 'yamunanagar')
(262, 'NISHU', 21, 'yamunanagar')
(263, 'HARSHIKA', 24, 'yamunanagar')
(264, 'HARSHIKA', 24, 'yamunanagar')
(265, 'NISHU', 18, 'yamunanagar')
(266, 'DEV', 23, 'yamunanagar')
(267, 'HARSHU', 22, 'yamunanagar')
(268, 'DEV', 20, 'yamunanagar')
(269, 'NISHU', 19, 'yamunanagar')
(270, 'HARSHIKA', 18, 'yamunanagar')
(271, 'HARSHU', 24, 'yamunanagar')
(272, 'HARSHU', 18, 'yamunanagar')
(273, 'HARSHIKA', 18, 'yamunanagar')
(274, 'HARSHIKA', 24, 'yamunanagar')
(275, 'NISHU', 22, 'yamunanagar')
(276, 'HARSHU', 23, 'yamunanagar')
(277, 'HARSHIKA', 19, 'yamunanagar')
(278, 'HARSHIKA', 20, 'yamunanagar')
(279, 'HARSHU', 18, 'yamunanagar')
(280, 'HARSHIKA', 21, 'yamunanagar')
(281, 'HARSHU', 20, 'yamunanagar')
(282, 'HARSHU', 20, 'yamunanagar')
(283, 'HARSHIKA', 22, 'yamunanagar')
(284, 'HARSHIKA', 18, 'yamunanagar')
(285, 'NISHU', 24, 'yamunanagar')
(286, 'DEV', 22, 'yamunanagar')
(287, 'HARSHU', 24, 'yamunanagar')
(288, 'HARSHU', 20, 'yamunanagar')
(289, 'DEV', 21, 'yamunanagar')
(290, 'HARSHU', 20, 'yamunanagar')
(291, 'HARSHIKA', 24, 'yamunanagar')
(292, 'NISHU', 23, 'yamunanagar')
(293, 'NISHU', 18, 'yamunanagar')
(294, 'HARSHIKA', 19, 'yamunanagar')
(295, 'HARSHU', 19, 'yamunanagar')
(296, 'NISHU', 22, 'yamunanagar')
(297, 'HARSHIKA', 18, 'yamunanagar')
(298, 'DEV', 23, 'yamunanagar')
(299, 'DEV', 21, 'yamunanagar')
(300, 'HARSHIKA', 23, 'yamunanagar')
(301, 'HARSHIKA', 22, 'yamunanagar')
(302, 'HARSHU', 19, 'yamunanagar')
(303, 'DEV', 22, 'yamunanagar')
(304, 'HARSHU', 20, 'yamunanagar')
(305, 'DEV', 21, 'yamunanagar')
(306, 'HARSHIKA', 23, 'yamunanagar')
(307, 'HARSHU', 19, 'yamunanagar')
(308, 'HARSHU', 20, 'yamunanagar')
(309, 'DEV', 23, 'yamunanagar')
(310, 'HARSHIKA', 24, 'yamunanagar')
(311, 'NISHU', 20, 'yamunanagar')
(312, 'HARSHU', 18, 'yamunanagar')
(313, 'NISHU', 21, 'yamunanagar')
(314, 'HARSHU', 24, 'yamunanagar')
(315, 'HARSHIKA', 24, 'yamunanagar')
(316, 'HARSHU', 24, 'yamunanagar')
(317, 'NISHU', 18, 'yamunanagar')
(318, 'DEV', 21, 'yamunanagar')
(319, 'DEV', 20, 'yamunanagar')
(320, 'HARSHU', 20, 'yamunanagar')
(321, 'HARSHIKA', 19, 'yamunanagar')
(322, 'HARSHU', 19, 'yamunanagar')
(323, 'NISHU', 21, 'yamunanagar')
(324, 'HARSHU', 20, 'yamunanagar')
(325, 'HARSHU', 20, 'yamunanagar')
(326, 'NISHU', 18, 'yamunanagar')
(327, 'DEV', 21, 'yamunanagar')
(328, 'HARSHIKA', 23, 'yamunanagar')
(329, 'DEV', 20, 'yamunanagar')
(330, 'NISHU', 23, 'yamunanagar')
(331, 'HARSHU', 18, 'yamunanagar')
(332, 'HARSHU', 23, 'yamunanagar')
(333, 'HARSHU', 23, 'yamunanagar')
(334, 'HARSHIKA', 24, 'yamunanagar')
(335, 'HARSHIKA', 18, 'yamunanagar')
(336, 'HARSHU', 18, 'yamunanagar')
(337, 'NISHU', 19, 'yamunanagar')
(338, 'HARSHU', 19, 'yamunanagar')
(339, 'HARSHIKA', 24, 'yamunanagar')
(340, 'HARSHIKA', 21, 'yamunanagar')
(341, 'NISHU', 18, 'yamunanagar')
(342, 'NISHU', 21, 'yamunanagar')
(343, 'NISHU', 21, 'yamunanagar')
(344, 'NISHU', 23, 'yamunanagar')
(345, 'HARSHIKA', 21, 'yamunanagar')
(346, 'HARSHU', 24, 'yamunanagar')
(347, 'HARSHIKA', 22, 'yamunanagar')
(348, 'HARSHU', 23, 'yamunanagar')
(349, 'DEV', 18, 'yamunanagar')
(350, 'HARSHIKA', 22, 'yamunanagar')
(351, 'NISHU', 19, 'yamunanagar')
(352, 'HARSHU', 18, 'yamunanagar')
(353, 'NISHU', 23, 'yamunanagar')
(354, 'HARSHIKA', 22, 'yamunanagar')
(355, 'NISHU', 24, 'yamunanagar')
(356, 'HARSHU', 19, 'yamunanagar')
(357, 'NISHU', 19, 'yamunanagar')
(358, 'NISHU', 24, 'yamunanagar')
(359, 'HARSHIKA', 18, 'yamunanagar')
(360, 'NISHU', 19, 'yamunanagar')
(361, 'NISHU', 19, 'yamunanagar')
(362, 'HARSHU', 19, 'yamunanagar')
(363, 'HARSHU', 22, 'yamunanagar')
(364, 'HARSHIKA', 23, 'yamunanagar')
(365, 'HARSHIKA', 24, 'yamunanagar')
(366, 'HARSHU', 20, 'yamunanagar')
(367, 'HARSHU', 19, 'yamunanagar')
(368, 'DEV', 20, 'yamunanagar')
(369, 'NISHU', 19, 'yamunanagar')
(370, 'HARSHU', 21, 'yamunanagar')
(371, 'HARSHU', 18, 'yamunanagar')
(372, 'NISHU', 18, 'yamunanagar')
(373, 'HARSHU', 20, 'yamunanagar')
(374, 'HARSHU', 24, 'yamunanagar')
(375, 'HARSHU', 19, 'yamunanagar')
(376, 'HARSHIKA', 18, 'yamunanagar')
(377, 'HARSHIKA', 23, 'yamunanagar')
(378, 'HARSHIKA', 23, 'yamunanagar')
(379, 'DEV', 20, 'yamunanagar')
(380, 'DEV', 23, 'yamunanagar')
(381, 'DEV', 19, 'yamunanagar')
(382, 'NISHU', 23, 'yamunanagar')
(383, 'HARSHIKA', 20, 'yamunanagar')
(384, 'HARSHIKA', 24, 'yamunanagar')
(385, 'NISHU', 24, 'yamunanagar')
(386, 'NISHU', 19, 'yamunanagar')
(387, 'HARSHIKA', 23, 'yamunanagar')
(388, 'DEV', 23, 'yamunanagar')
(389, 'DEV', 22, 'yamunanagar')
(390, 'DEV', 19, 'yamunanagar')
(391, 'HARSHU', 22, 'yamunanagar')
(392, 'HARSHIKA', 19, 'yamunanagar')
(393, 'NISHU', 21, 'yamunanagar')
(394, 'NISHU', 19, 'yamunanagar')
(395, 'NISHU', 22, 'yamunanagar')
(396, 'HARSHU', 21, 'yamunanagar')
(397, 'HARSHIKA', 23, 'yamunanagar')
(398, 'HARSHIKA', 18, 'yamunanagar')
(399, 'HARSHU', 22, 'yamunanagar')
(400, 'DEV', 19, 'yamunanagar')
(401, 'DEV', 24, 'yamunanagar')
(402, 'DEV', 19, 'yamunanagar')
(403, 'DEV', 24, 'yamunanagar')
(404, 'NISHU', 18, 'yamunanagar')
(405, 'DEV', 20, 'yamunanagar')
(406, 'DEV', 24, 'yamunanagar')
(407, 'DEV', 21, 'yamunanagar')
(408, 'NISHU', 20, 'yamunanagar')
(409, 'NISHU', 24, 'yamunanagar')
(410, 'DEV', 24, 'yamunanagar')
(411, 'HARSHIKA', 22, 'yamunanagar')
(412, 'DEV', 21, 'yamunanagar')
(413, 'DEV', 20, 'yamunanagar')
(414, 'HARSHU', 21, 'yamunanagar')
(415, 'NISHU', 19, 'yamunanagar')
(416, 'HARSHU', 18, 'yamunanagar')
(417, 'DEV', 20, 'yamunanagar')
(418, 'HARSHU', 23, 'yamunanagar')
(419, 'HARSHU', 24, 'yamunanagar')
(420, 'HARSHU', 18, 'yamunanagar')
(421, 'NISHU', 18, 'yamunanagar')
(422, 'HARSHIKA', 23, 'yamunanagar')
(423, 'DEV', 22, 'yamunanagar')
(424, 'HARSHIKA', 23, 'yamunanagar')
(425, 'NISHU', 23, 'yamunanagar')
(426, 'DEV', 24, 'yamunanagar')
(427, 'NISHU', 20, 'yamunanagar')
(428, 'HARSHU', 18, 'yamunanagar')
(429, 'NISHU', 22, 'yamunanagar')
(430, 'NISHU', 18, 'yamunanagar')
(431, 'HARSHU', 24, 'yamunanagar')
(432, 'HARSHIKA', 19, 'yamunanagar')
(433, 'DEV', 18, 'yamunanagar')
(434, 'HARSHU', 23, 'yamunanagar')
(435, 'HARSHIKA', 20, 'yamunanagar')
(436, 'HARSHU', 21, 'yamunanagar')
(437, 'NISHU', 20, 'yamunanagar')
(438, 'HARSHU', 24, 'yamunanagar')
(439, 'NISHU', 18, 'yamunanagar')
(440, 'HARSHU', 22, 'yamunanagar')
(441, 'HARSHU', 20, 'yamunanagar')
(442, 'HARSHIKA', 24, 'yamunanagar')
(443, 'HARSHIKA', 22, 'yamunanagar')
(444, 'NISHU', 21, 'yamunanagar')
(445, 'HARSHU', 24, 'yamunanagar')
(446, 'NISHU', 20, 'yamunanagar')
(447, 'HARSHIKA', 22, 'yamunanagar')
(448, 'DEV', 21, 'yamunanagar')
(449, 'DEV', 20, 'yamunanagar')
(450, 'DEV', 22, 'yamunanagar')
(451, 'DEV', 19, 'yamunanagar')
(452, 'DEV', 18, 'yamunanagar')
(453, 'HARSHU', 18, 'yamunanagar')
(454, 'HARSHIKA', 18, 'yamunanagar')
(455, 'HARSHU', 23, 'yamunanagar')
(456, 'DEV', 18, 'yamunanagar')
(457, 'HARSHIKA', 23, 'yamunanagar')
(458, 'DEV', 19, 'yamunanagar')
(459, 'NISHU', 23, 'yamunanagar')
(460, 'HARSHU', 19, 'yamunanagar')
(461, 'DEV', 20, 'yamunanagar')
(462, 'NISHU', 22, 'yamunanagar')
(463, 'NISHU', 24, 'yamunanagar')
(464, 'HARSHU', 18, 'yamunanagar')
(465, 'HARSHIKA', 22, 'yamunanagar')
(466, 'DEV', 19, 'yamunanagar')
(467, 'NISHU', 23, 'yamunanagar')
(468, 'HARSHU', 24, 'yamunanagar')
(469, 'HARSHU', 18, 'yamunanagar')
(470, 'HARSHU', 18, 'yamunanagar')
(471, 'HARSHU', 24, 'yamunanagar')
(472, 'HARSHU', 20, 'yamunanagar')
(473, 'NISHU', 21, 'yamunanagar')
(474, 'DEV', 22, 'yamunanagar')
(475, 'DEV', 21, 'yamunanagar')
(476, 'NISHU', 23, 'yamunanagar')
(477, 'HARSHIKA', 19, 'yamunanagar')
(478, 'DEV', 23, 'yamunanagar')
(479, 'DEV', 18, 'yamunanagar')
(480, 'HARSHIKA', 24, 'yamunanagar')
(481, 'NISHU', 19, 'yamunanagar')
(482, 'HARSHU', 18, 'yamunanagar')
(483, 'HARSHIKA', 21, 'yamunanagar')
(484, 'HARSHIKA', 24, 'yamunanagar')
(485, 'HARSHU', 20, 'yamunanagar')
(486, 'DEV', 23, 'yamunanagar')
(487, 'NISHU', 23, 'yamunanagar')
(488, 'HARSHU', 20, 'yamunanagar')
(489, 'HARSHU', 21, 'yamunanagar')
(490, 'DEV', 21, 'yamunanagar')
(491, 'NISHU', 24, 'yamunanagar')
(492, 'HARSHIKA', 21, 'yamunanagar')
(493, 'HARSHIKA', 19, 'yamunanagar')
(494, 'NISHU', 24, 'yamunanagar')
(495, 'NISHU', 21, 'yamunanagar')
(496, 'NISHU', 23, 'yamunanagar')
(497, 'DEV', 22, 'yamunanagar')
(498, 'DEV', 22, 'yamunanagar')
(499, 'DEV', 18, 'yamunanagar')
(500, 'NISHU', 20, 'yamunanagar')
(501, 'HARSHIKA', 23, 'yamunanagar')
(502, 'DEV', 18, 'yamunanagar')
(503, 'HARSHIKA', 21, 'yamunanagar')
(504, 'HARSHU', 24, 'yamunanagar')
(505, 'HARSHU', 20, 'yamunanagar')
(506, 'HARSHU', 22, 'yamunanagar')
(507, 'HARSHU', 23, 'yamunanagar')
(508, 'DEV', 22, 'yamunanagar')
(509, 'HARSHIKA', 24, 'yamunanagar')
(510, 'HARSHU', 20, 'yamunanagar')
(511, 'HARSHU', 19, 'yamunanagar')
(512, 'NISHU', 22, 'yamunanagar')
(513, 'DEV', 18, 'yamunanagar')
(514, 'DEV', 20, 'yamunanagar')
(515, 'NISHU', 19, 'yamunanagar')
(516, 'NISHU', 22, 'yamunanagar')
(517, 'HARSHU', 19, 'yamunanagar')
(518, 'DEV', 22, 'yamunanagar')
(519, 'HARSHIKA', 20, 'yamunanagar')
(520, 'HARSHIKA', 20, 'yamunanagar')
(521, 'DEV', 21, 'yamunanagar')
(522, 'HARSHIKA', 23, 'yamunanagar')
(523, 'NISHU', 19, 'yamunanagar')
(524, 'DEV', 23, 'yamunanagar')
(525, 'NISHU', 24, 'yamunanagar')
(526, 'HARSHIKA', 21, 'yamunanagar')
(527, 'HARSHIKA', 19, 'yamunanagar')
(528, 'NISHU', 22, 'yamunanagar')
(529, 'HARSHU', 18, 'yamunanagar')
(530, 'NISHU', 21, 'yamunanagar')
(531, 'NISHU', 22, 'yamunanagar')
(532, 'HARSHU', 23, 'yamunanagar')
(533, 'HARSHU', 22, 'yamunanagar')
(534, 'HARSHU', 24, 'yamunanagar')
(535, 'DEV', 19, 'yamunanagar')
(536, 'DEV', 24, 'yamunanagar')
(537, 'HARSHIKA', 24, 'yamunanagar')
(538, 'HARSHU', 18, 'yamunanagar')
(539, 'HARSHU', 19, 'yamunanagar')
(540, 'HARSHU', 20, 'yamunanagar')
(541, 'HARSHIKA', 19, 'yamunanagar')
(542, 'HARSHIKA', 24, 'yamunanagar')
(543, 'HARSHU', 23, 'yamunanagar')
(544, 'NISHU', 19, 'yamunanagar')
(545, 'HARSHU', 24, 'yamunanagar')
(546, 'HARSHIKA', 22, 'yamunanagar')
(547, 'DEV', 19, 'yamunanagar')
(548, 'NISHU', 24, 'yamunanagar')
(549, 'HARSHU', 18, 'yamunanagar')
(550, 'HARSHU', 20, 'yamunanagar')
(551, 'HARSHIKA', 20, 'yamunanagar')
(552, 'DEV', 24, 'yamunanagar')
(553, 'HARSHU', 23, 'yamunanagar')
(554, 'HARSHU', 21, 'yamunanagar')
(555, 'DEV', 23, 'yamunanagar')
(556, 'HARSHU', 19, 'yamunanagar')
(557, 'HARSHU', 18, 'yamunanagar')
(558, 'HARSHIKA', 18, 'yamunanagar')
(559, 'DEV', 21, 'yamunanagar')
(560, 'HARSHU', 21, 'yamunanagar')
(561, 'NISHU', 20, 'yamunanagar')
(562, 'HARSHIKA', 21, 'yamunanagar')
(563, 'DEV', 22, 'yamunanagar')
(564, 'HARSHIKA', 20, 'yamunanagar')
(565, 'NISHU', 22, 'yamunanagar')
(566, 'NISHU', 22, 'yamunanagar')
(567, 'HARSHIKA', 24, 'yamunanagar')
(568, 'HARSHIKA', 18, 'yamunanagar')
(569, 'HARSHIKA', 18, 'yamunanagar')
(570, 'HARSHIKA', 18, 'yamunanagar')
(571, 'HARSHU', 22, 'yamunanagar')
(572, 'NISHU', 19, 'yamunanagar')
(573, 'DEV', 18, 'yamunanagar')
(574, 'NISHU', 23, 'yamunanagar')
(575, 'DEV', 23, 'yamunanagar')
(576, 'NISHU', 18, 'yamunanagar')
(577, 'DEV', 22, 'yamunanagar')
(578, 'DEV', 18, 'yamunanagar')
(579, 'DEV', 22, 'yamunanagar')
(580, 'DEV', 20, 'yamunanagar')
(581, 'DEV', 21, 'yamunanagar')
(582, 'NISHU', 24, 'yamunanagar')

<div style="
background:#FFF8FA;
border-left:6px solid #D89CA9;
border-radius:4px;
padding:12px 18px;
margin:6px 0;">
<h4 style="
color:#8A5A66;
margin:0;
font-size:17px;
font-weight:600;">
◇ Creating dataframe from database records 
</h4>
</div>

In [44]:
db = pd.DataFrame(results)
db

          0         1   2            3
0         1  HARSHIKA  21  yamunanagar
1         2    HARSHU  20  yamunanagar
2         3     NISHU  18  yamunanagar
3         4  HARSHIKA  18  yamunanagar
4         5  HARSHIKA  22  yamunanagar
...     ...       ...  ..          ...
9995   9996     NISHU  21  yamunanagar
9996   9997       DEV  20  yamunanagar
9997   9998    HARSHU  19  yamunanagar
9998   9999    HARSHU  22  yamunanagar
9999  10000       DEV  24  yamunanagar

[10000 rows x 4 columns]

<div style="
background:#FFF8FA;
border-left:10px solid #D89CA9;
border-right:10px solid #D89CA9;
border-radius:12px;
padding:22px;
margin:10px 0;
text-align:center;">

<h2 style="color:#8A5A66;">
Thank You for reviewing this project.
</h2>



</div>